# Generated by Django 5.0.3 on 2024-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGov',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=200)),
                ('cpf', models.CharField(default='', max_length=30)),
                ('session_id', models.CharField(default='', max_length=300)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('internal_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGov',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=30)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('iat', models.CharField(default='', max_length=100)),
                ('exp', models.CharField(default='', max_length=100)),
                ('nonce', models.CharField(default='', max_length=100)),
                ('last_update', models.CharField(default='', max_length=200)),
                ('ap_mac', models.CharField(blank=True, default='', max_length=30)),
                ('client_mac', models.CharField(blank=True, default='', max_length=30)),
                ('wlan', models.CharField(blank=True, default='', max_length=30)),
                ('ip', models.CharField(blank=True, default='', max_length=200)),
                ('login_wifi', models.CharField(blank=True, default='', max_length=100)),
                ('logout_wifi', models.CharField(blank=True, default='', max_length=100)),
                ('internal_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'names',
                'ordering': ['-login_wifi'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=30)),
                ('termos', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
